.Net Core Application.WebApp/ElectronicSalesManagement/ElectronicSalesManagement/Controllers/CartController.cs
using Core.Entities;
using ElectronicSalesManagement.AjaxModels;
using ElectronicSalesManagement.Models;
using ElectronicSalesManagement.ViewModels;
using Infrastructure.Persistance.IRepository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace ElectronicSalesManagement.Controllers
{
    public class CartController : Controller
    {
        private readonly ICategoryRepository categoryRepository;
        private readonly ISaleRepository saleRepository;
        private readonly IProductRepository productRepository;
        private readonly IProvinceRepository provinceRepository;
        private readonly IDistrictRepository districtRepository;
        private readonly IWardRepository wardRepository;
        private readonly IAccountRepository accountRepository;
        private readonly ICustomerRepository customerRepository;
        private readonly IOrderRepository orderRepository;
        private readonly IDetailOrderRepository detailOrderRepository;

        public CartController(ICategoryRepository categoryRepository, ISaleRepository saleRepository,
            IProductRepository productRepository, IProvinceRepository provinceRepository,
            IDistrictRepository districtRepository, IWardRepository wardRepository,
            IAccountRepository accountRepository, ICustomerRepository customerRepository,
            IOrderRepository orderRepository, IDetailOrderRepository detailOrderRepository)
        {
            this.categoryRepository = categoryRepository;
            this.saleRepository = saleRepository;
            this.productRepository = productRepository;
            this.provinceRepository = provinceRepository;
            this.districtRepository = districtRepository;
            this.wardRepository = wardRepository;
            this.accountRepository = accountRepository;
            this.customerRepository = customerRepository;
            this.orderRepository = orderRepository;
            this.detailOrderRepository = detailOrderRepository;
        }
        public IActionResult Index()
        {
            ViewData["Categories"] = categoryRepository.Categories();
            var SESSION_CART = HttpContext.Session.GetString("cart");
            List<Cart> list_cart = new List<Cart>();
            if (SESSION_CART != null)
            {
                list_cart = JsonConvert.DeserializeObject<List<Cart>>(SESSION_CART);
            }
            ModelView MV = new ModelView
            {
                list_cart = list_cart,
                Sales = saleRepository.Sales()
            };
            return View(MV);
        }

        #region .
        //[Route("nam-mo-moi-biet-duoc-link-nay")]
        #endregion

        public IActionResult Checkout()
        {
            ViewData["Categories"] = categoryRepository.Categories();
            var username = HttpContext.Session.GetString("login");
            if(username == null)
            {
                Response.Redirect("/Login/Index");
            }

            ModelView MV = new ModelView
            {
                Provinces = provinceRepository.Provinces()
            };

            return View(MV);
        }

        [HttpPost]
        public JsonResult GetTotalMoney_ForCheck()
        {
            var SESSION_CART = HttpContext.Session.GetString("cart");
            var money = "Total: 0 VNĐ";
            double totalMoney = 0;
            if (SESSION_CART != null)
            {
                List<Cart> list = JsonConvert.DeserializeObject<List<Cart>>(SESSION_CART);
                foreach (var i in list)
                {
                    totalMoney += double.Parse(i.IntoMoney);
                }

                money = "Total: " + totalMoney.ToString("#,##0").Replace(",", ".") + " VNĐ";
            }
            return Json(money);
        }

        [HttpPost]
        public JsonResult removeProductFromCart([FromBody] RemoveProductFromCart model)
        {
            var idProduct = int.Parse(model.IDProduct);
            var message = "Remove successed.!!!";

            var SESSION_CART = HttpContext.Session.GetString("cart");
            List<Cart> list = JsonConvert.DeserializeObject<List<Cart>>(SESSION_CART);
            foreach (var item in list)
            {
                if (item.Product_ID == idProduct)
                {
                    list.Remove(item);
                    break;
                }
            }
            HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(list));

            return Json(message);
        }

        [HttpPost]
        public JsonResult UpdateCart([FromBody] UpdateCart model)
        {
            var idProduct = int.Parse(model.IDProduct);
            var quantity = model.Quantity;

            Product p = productRepository.FindByID(idProduct);

            int percentSale = int.Parse(saleRepository.Sales().Where(s => int.Parse(s.ID_SaleParent) == p.ID_Sale).FirstOrDefault().Percent_sale);
            double saleMoney = double.Parse(p.Price) - (double.Parse(p.Price) * double.Parse(percentSale.ToString()) / 100);

            var SESSION_CART = HttpContext.Session.GetString("cart");

            List<Cart> list = JsonConvert.DeserializeObject<List<Cart>>(SESSION_CART);

            if (int.Parse(quantity) < p.Amount)
            {
                foreach (var item in list)
                {
                    if (item.Product_ID == idProduct)
                    {
                        item.Amount = int.Parse(quantity);
                        item.IntoMoney = ((double.Parse(quantity) * saleMoney)).ToString();
                        break;
                    }
                }
            }
            else
            {
                foreach (var item in list)
                {
                    if (item.Product_ID == idProduct)
                    {
                        item.Amount = p.Amount;
                        item.IntoMoney = ((double.Parse((p.Amount).ToString()) * saleMoney)).ToString();
                        break;
                    }
                }
            }

            HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(list));

            return Json("ok");
        }

        [HttpPost]
        public JsonResult GetDistrict([FromBody] GetDataNational model)
        {
            var idProvince = int.Parse(model.IDProvince);

            IEnumerable<District> districts = districtRepository.Districts().Where(d => d.ID_Province == idProvince);
            var html = "";
            foreach (var i in districts)
            {
                html += "<option value='" + i.ID_District + "'>" + i.Name + "</option>";
            }

            return Json(html);
        }

        [HttpPost]
        public JsonResult GetWard([FromBody] GetDataNational model)
        {
            var idDistrict = int.Parse(model.IDDistrict);

            IEnumerable<Ward> wards = wardRepository.Wards().Where(w => w.ID_District == idDistrict);
            var html = "";
            foreach (var i in wards)
            {
                html += "<option value='" + i.ID_Ward + "'>" + i.Name + "</option>";
            }

            return Json(html);
        }

        [HttpPost]
        public JsonResult CheckoutHandler([FromBody] Checkout model)
        {
            var firstName = model.FirstName;
            var lastName = model.LastName;
            var email = model.Email;
            var phone = model.Phone;
            var IDProvince = model.IDProvince;
            var IDDistrict = model.IDDistrict;
            var IDWard = model.IDWard;
            var address = model.Address;
            var note = model.Note;

            var SESSION_LOGIN = HttpContext.Session.GetString("login");
            var username = JsonConvert.DeserializeObject<String>(SESSION_LOGIN);

            var SESSION_CART = HttpContext.Session.GetString("cart");
            List<Cart> list = JsonConvert.DeserializeObject<List<Cart>>(SESSION_CART);

            // get ID Account
            var IDAccount = accountRepository.Accounts().Where(a => a.Username == username).FirstOrDefault().ID_Account;

            // get data national
            var provinceName = provinceRepository.FindByID(int.Parse(IDProvince)).Name;
            var districtName = districtRepository.FindByID(int.Parse(IDDistrict)).Name;
            var wardName = wardRepository.FindByID(int.Parse(IDWard)).Name;

            var fullName = firstName + " " + lastName;
            var fullAdress = address + ", " + wardName + " Ward, " + districtName + " District, " + provinceName + " Province";

            // check exist customer
            Customer c = customerRepository.Customers().Where(c => c.FullName.ToLower() == fullName.ToLower() 
                                                                        && c.Address == fullAdress)
                                                        .FirstOrDefault();
            var IDCustomer = 0;
            if (c == null)
            {
                customerRepository.createCustomer(new Customer
                {
                    FullName = fullName,
                    Address = fullAdress,
                    Phone = phone,
                    ID_Account = IDAccount
                });
                IDCustomer = customerRepository.Customers().LastOrDefault().ID_Customer;
            }
            else
            {
                IDCustomer = c.ID_Customer;
            }

            // get Total Money Cart
            var totalMoney = list.Sum(p => double.Parse(p.IntoMoney));

            // create order
            orderRepository.createOrder(new Order
            {
                ID_Customer = IDCustomer,
                Receiver = fullName,
                Address = fullAdress,
                Phone = phone,
                TotalMoney = totalMoney.ToString(),

.Net Core Application.WebApp/ElectronicSalesManagement/ElectronicSalesManagement/Controllers/HistoryController.cs
using Core.Entities;
using ElectronicSalesManagement.ViewModels;
using Infrastructure.Persistance.IRepository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElectronicSalesManagement.Controllers
{
    public class HistoryController : Controller
    {
        private readonly ICategoryRepository categoryRepository;
        private readonly ICustomerRepository customerRepository;
        private readonly IOrderRepository orderRepository;
        private readonly IDetailOrderRepository detailOrderRepository;
        private readonly IProductRepository productRepository;
        private readonly IAccountRepository accountRepository;
        public HistoryController(IAccountRepository accountRepository,ICategoryRepository categoryRepository,
            ICustomerRepository customerRepository,IOrderRepository orderRepository,
            IDetailOrderRepository detailOrderRepository,IProductRepository productRepository)
        {
            this.categoryRepository = categoryRepository;
            this.customerRepository = customerRepository;
            this.orderRepository = orderRepository;
            this.detailOrderRepository = detailOrderRepository;
            this.productRepository = productRepository;
            this.accountRepository = accountRepository;
        }

        public IActionResult Index()
        {
            ViewData["Categories"] = categoryRepository.Categories();
            if (!checkSession())
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                var user = HttpContext.Session.GetString("login");
                user = JsonConvert.DeserializeObject<String>(user);
                Account acc = accountRepository.Accounts().Where(m => m.Username == user).FirstOrDefault();
                ModelView VM = new ModelView
                {
                    Orders = orderRepository.Orders(),
                    Categories = categoryRepository.Categories(),
                    Customers = customerRepository.Customers(),
                    account = acc
                };
                return View(VM);
            }
        }

        public IActionResult DetailOrder(int id)
        {
            String user = HttpContext.Session.GetString("login");
            if (!checkSession())
            {
                Response.Redirect("/Login/Index");
            }
            var order = orderRepository.FindByID(id);
            var lstorderDetail = new List<DetailOrder>();
            foreach (var i in detailOrderRepository.DetailOrders())
            {
                if (i.ID_Order == order.ID_Order)
                {
                    lstorderDetail.Add(i);
                }
            }
            ModelView VM = new ModelView
            {
                Products = productRepository.Products(),
                Categories = categoryRepository.Categories(),
                Orders = orderRepository.Orders(),
                DetailOrders = lstorderDetail,
                order = order
            };
            ViewData["Categories"] = categoryRepository.Categories();
            return View(VM);
        }

        public Boolean checkSession()
        {
            String user = HttpContext.Session.GetString("login");
            if (user != null)
            {
                return true;
            }
            return false;
        }
    }
}

.Net Core Application.WebApp/ElectronicSalesManagement/ElectronicSalesManagement/Controllers/LoginController.cs
using Core.Entities;
using ElectronicSalesManagement.Models;
using Infrastructure.Persistance.DBcontext;
using Infrastructure.Persistance.IRepository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace ElectronicSalesManagement.Controllers
{
    public class LoginController : Controller
    {
        private readonly IAccountRepository accountRepository;

        public LoginController(IAccountRepository _accountRepository)
        {
            accountRepository = _accountRepository;
        }

        public IActionResult Index()
        {
            String user = HttpContext.Session.GetString("login");

            if (checkSession())
            {
                Response.Redirect("/Home/Index");
            }
            return View(new LoginModel());
        }

        [HttpPost]
        public IActionResult Index(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                String user = model.Username;
                String pass = SeedData.ToMD5(model.Password);

                Account acc = accountRepository.Accounts().Where(p => p.Username == user && p.Password == pass).FirstOrDefault();

                if (acc != null)
                {
                    HttpContext.Session.SetString("login", JsonConvert.SerializeObject(acc.Username));
                    Response.Redirect("/Home/Index");
                }
                else
                {
                    Response.Redirect("/Login/Index");
                }

            }
            return View();
        }

        public void Logout()
        {
            HttpContext.Session.Remove("login");
            Response.Redirect("/Home/Index");
        }

        public IActionResult Register()
        {
            if (checkSession())
            {
                Response.Redirect("/Home/Index");
            }
            return View(new RegisterModel());
        }

        public static string ToMD5(string str)
        {

            MD5CryptoServiceProvider md5 = new MD5CryptoServiceProvider();

            byte[] bHash = md5.ComputeHash(Encoding.UTF8.GetBytes(str));

            StringBuilder sbHash = new StringBuilder();

            foreach (byte b in bHash)
            {

                sbHash.Append(String.Format("{0:x2}", b));

            }
            return sbHash.ToString();

        }

        [HttpPost]
        public IActionResult Register(RegisterModel rm)
        {

            if (ModelState.IsValid) 
            {          

                var a = new Account();
                a.Username = rm.Username;
                a.Password = ToMD5(rm.Password);
                a.Email = rm.Email;
                a.Status = "Hoạt động";
                a.DateActive = DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss");
                accountRepository.createAccount(a);
                return RedirectToAction("Index");
            }
            return View();
        }

        public Boolean checkSession()
        {
            String user = HttpContext.Session.GetString("login");
            if (user != null)
            {
                return true;
            }
            return false;
        }
    }
}

.Net Core Application.WebApp/ElectronicSalesManagement/ElectronicSalesManagement/Views/Shared/_CategoryAndSlideshow.cshtml
<section class="bg__white">
    <div class="container">
        <div class="row">
            <div class="col-md-9 col-lg-9 col-sm-9 col-xs-12 float-left-style">
                <div class="mySlides">
                    <img src="~/images/Image_ElectronicSale/slide_1.png"
                         style="left:0;object-fit: cover;width:100%;" />
                </div>
                <div class="mySlides">
                    <img src="~/images/Image_ElectronicSale/slide_2.png"
                         style="left:0;object-fit: cover;width:100%;" />
                </div>
                <div class="mySlides">
                    <img src="~/images/Image_ElectronicSale/slide_3.png"
                         style="left:0;object-fit: cover;width:100%;" />
                </div>

                <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                <a class="next" onclick="plusSlides(1)">&#10095;</a>

                <div style="text-align:center">
                    <span class="dot" onclick="currentSlide(1)"></span>
                    <span class="dot" onclick="currentSlide(2)"></span>
                    <span class="dot" onclick="currentSlide(3)"></span>
                </div>

                <style>
                    /* Hide the images by default */
                    .mySlides {
                        display: none;
                    }

                    /* Next & previous buttons */
                    .prev, .next {
                        cursor: pointer;
                        position: absolute;
                        top: 50%;
                        width: auto;
                        margin-top: -22px;
                        padding: 16px;
                        color: white;
                        font-weight: bold;
                        font-size: 18px;
                        transition: 0.6s ease;
                        border-radius: 0 3px 3px 0;
                        user-select: none;
                    }

                    /* Position the "next button" to the right */
                    .next {
                        right: 15px;
                        border-radius: 3px 0 0 3px;
                    }

                        /* On hover, add a black background color with a little bit see-through */
                        .prev:hover, .next:hover {
                            background-color: rgba(0,0,0,0.8);
                        }

                    /* The dots/bullets/indicators */
                    .dot {
                        cursor: pointer;
                        height: 15px;
                        width: 15px;
                        margin: 5px 2px;
                        background-color: #bbb;
                        border-radius: 50%;
                        display: inline-block;
                        transition: background-color 0.6s ease;
                    }

                        .dot:hover {
                            background-color: #717171;
                        }
                </style>
                <script>
                    //#region showSlide(slide)
                    var slideIndex = 1;
                    showSlides(slideIndex);

                    // Next/previous controls
                    function plusSlides(n) {
                        showSlides(slideIndex += n);
                    }

                    // Thumbnail image controls
                    function currentSlide(n) {
                        showSlides(slideIndex = n);
                    }

                    function showSlides(n) {
                        var i;
                        var slides = document.getElementsByClassName("mySlides");
                        var dots = document.getElementsByClassName("dot");
                        if (n > slides.length) { slideIndex = 1 }
                        if (n < 1) { slideIndex = slides.length }
                        for (i = 0; i < slides.length; i++) {
                            slides[i].style.display = "none";
                        }
                        for (i = 0; i < dots.length; i++) {
                            dots[i].className = dots[i].className.replace(" active", "");
                        }
                        slides[slideIndex - 1].style.display = "block";
                        dots[slideIndex - 1].className += " active";
                    }
                    //#endregion
                    //#region automatic slideShow()
                    var slideIndex = 0;
                    showSlides();

                    function showSlides() {
                        var i;
                        var slides = document.getElementsByClassName("mySlides");
                        for (i = 0; i < slides.length; i++) {
                            slides[i].style.display = "none";
                        }
                        slideIndex++;
                        if (slideIndex > slides.length) { slideIndex = 1 }
                        slides[slideIndex - 1].style.display = "block";
                        setTimeout(showSlides, 5000); // Change image every 5 seconds
                    }
                                    //#endregion
                </script>
            </div>
            <div class="col-md-3 col-lg-3 col-sm-4 col-xs-12 float-right-style">
                <div class="categories-menu mrg-xs">
                    <div class="category-heading">
                        <h3>Categories</h3>
                    </div>
                    <div class="category-menu-list">
                        <ul>
                            @{
                                foreach (Category i in ViewData["Categories"] as List<Category>)
                                {
                                    if (i.ID_Category != 2)
                                    {
                                        <li><a href="/Product/Index/@i.ID_Category">&ensp;@i.Name</a></li>
                                    }
                                }
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

.Net Core Application.WebApp/ElectronicSalesManagement/ElectronicSalesManagement/Views/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Http;
@{
    var data = Context.Session.GetString("cart");

    int coutCart = 0;
    if (data == null)
    {
        coutCart = 0;
    }
    else
    {
        var data2 = Context.Session.GetString("cart");
        List<Cart> dataCart = JsonConvert.DeserializeObject<List<Cart>>(data2);

        coutCart = dataCart.Sum(x => x.Amount);

    }
}
<header id="header" class="htc-header header--3 bg__white">

    <div id="sticky-header-with-topbar" class="mainmenu__area sticky__header">
        <div class="container">
            <div class="row">
                <div class="col-md-2 col-lg-2 col-sm-3 col-xs-3">
                    <div class="logo">
                        <a asp-controller="Home" asp-action="Index">
                            <img style="border-radius:3px" src="~/images/logo/logo.jpg" alt="logo">
                        </a>
                    </div>
                </div>

                <div class="col-md-8 col-lg-7 col-sm-6 col-xs-6">
                    <nav class="mainmenu__nav hidden-xs hidden-sm">
                        <ul class="main__menu">
                            <li class="drop"><a asp-controller="Home" asp-action="Index">Home</a></li>
                            <li class="drop">
                                <a asp-controller="Product" asp-action="Index" asp-route-idCategory="0">Products</a>
                            </li>
                            <li class="drop">
                                <a asp-controller="History" asp-action="Index">History</a>
                            </li>
                            <li class="drop">
                                <a asp-controller="Contact" asp-action="Index">Contact Us</a>
                            </li>
                        </ul>
                    </nav>
                </div>

                <div class="col-md-2 col-sm-4 col-xs-3 col-lg-5">
                    <ul class="menu-extra">
                        <li>
                            <span id="totalMoneyHeader"
                                  style="color:red;font-size:13px;font-weight:600;font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"></span>&ensp;
                            <a asp-controller="Cart" asp-action="Index">
                                    <i class="fas fa-shopping-cart" style="font-size:25px;"></i>
                                    <span style="   font-weight:600;font-size:13px;padding:1px 6.5px 1px 6.5px;
                                                    position:relative;bottom:18px;right:14px;
                                                    border:2px solid white;background-color:#FF0000;color:white;
                                                    border-radius:50%">@coutCart</span>
                            </a>
                        </li>
                        @{
                            String username = Context.Session.GetString("login");
                            if (username != null)
                            {
                                username = JsonConvert.DeserializeObject<String>(username);
                                <li>
                                    Hello: <a asp-controller="Account" asp-action="Detail">@username</a>
                                    <a class="nav-link nav-icons text-white font-weight-bold text-center bg-gradient-blue"
                                       style="border-radius:10px;font-size:18px;margin-left:5px;"
                                       asp-controller="Login"
                                       asp-action="Logout"><i class="fa fa-sign-out-alt" style="font-size:22px;"></i></a>
                                </li>
                            }
                            else
                            {
                                <li><a asp-controller="Login" asp-action="Index"><span class="fa fa-user" style="font-size:22px;"></span></a></li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="body__overlay"></div>

.Net Core Application.WebApp/ElectronicSalesManagement/ElectronicSalesManagement/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewData["Title"]</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.ico">


    <!-- All css files are included here. -->
    <!-- Bootstrap fremwork main css -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <!-- Owl Carousel main css -->
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <!-- This core.css file contents all plugings css file. -->
    <link rel="stylesheet" href="~/css/core.css">
    <!-- Theme shortcodes/elements style -->
    <link rel="stylesheet" href="~/css/shortcode/shortcodes.css">
    <!-- Theme main style -->
    <link rel="stylesheet" href="~/style.css">
    <!-- Responsive css -->
    <link rel="stylesheet" href="~/css/responsive.css">
    <!-- User style -->
    <link href="~/css/custom.css" rel="stylesheet" />

    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <script src="~/lib/font-awesome/js/all.min.js"></script>

    <!-- Modernizr JS -->
    <script src="~/js/vendor/modernizr-2.8.3.min.js"></script>
</head>
<body>
    <div class="wrapper fixed__footer">
        <partial name="_Header" />
        @RenderBody()
        <partial name="_Footer" />
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- new ^^ -->
    <script src="~/js/vendor/jquery-1.12.0.min.js"></script>
    <!-- Bootstrap framework js -->
    <script src="~/js/bootstrap.min.js"></script>
    <!-- All js plugins included in this file. -->
    <script src="~/js/plugins.js"></script>
    <script src="~/js/slick.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <!-- Waypoints.min.js. -->
    <script src="~/js/waypoints.min.js"></script>
    <!-- Main js file that contents all jQuery plugins activation. -->
    <script src="~/js/main.js"></script>
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @RenderSection("Login", required: false);
</body>
</html>